import {items} from './type-items';

export const ITEMS:  items[] = [{"avatar":"https://robohash.org/quosautatque.bmp?size=50x50&set=set1","name":"Margarette Hearfield","id":1,"position":"Safety Technician IV","department":"Marketing","email":"mhearfield0@baidu.com"},
{"avatar":"https://robohash.org/ipsadelenitiad.bmp?size=50x50&set=set1","name":"Meredith Niblett","id":2,"position":"Structural Engineer","department":"Business Development","email":"mniblett1@java.com"},
{"avatar":"https://robohash.org/remfugaea.jpg?size=50x50&set=set1","name":"Ira Mabbs","id":3,"position":"Paralegal","department":"Training","email":"imabbs2@amazon.co.uk"},
{"avatar":"https://robohash.org/quaeetsimilique.bmp?size=50x50&set=set1","name":"Ivor Turmell","id":4,"position":"Computer Systems Analyst IV","department":"Training","email":"iturmell3@g.co"},
{"avatar":"https://robohash.org/sedvoluptasreprehenderit.jpg?size=50x50&set=set1","name":"Ellene Matthai","id":5,"position":"Editor","department":"Research and Development","email":"ematthai4@si.edu"},
{"avatar":"https://robohash.org/veritatisexpeditamolestiae.jpg?size=50x50&set=set1","name":"Ellis Jerrams","id":6,"position":"Design Engineer","department":"Business Development","email":"ejerrams5@reddit.com"},
{"avatar":"https://robohash.org/sitquasiminima.bmp?size=50x50&set=set1","name":"Drusilla Walkley","id":7,"position":"Sales Representative","department":"Human Resources","email":"dwalkley6@google.ru"},
{"avatar":"https://robohash.org/ametquodolorem.bmp?size=50x50&set=set1","name":"Earle Yokelman","id":8,"position":"Food Chemist","department":"Product Management","email":"eyokelman7@wikispaces.com"},
{"avatar":"https://robohash.org/utvoluptateet.bmp?size=50x50&set=set1","name":"Lira Beardsworth","id":9,"position":"VP Quality Control","department":"Human Resources","email":"lbeardsworth8@imgur.com"},
{"avatar":"https://robohash.org/perferendissintid.jpg?size=50x50&set=set1","name":"Marlon Garnar","id":10,"position":"Accounting Assistant I","department":"Engineering","email":"mgarnar9@wiley.com"},
{"avatar":"https://robohash.org/voluptatemsitdolor.bmp?size=50x50&set=set1","name":"Faythe Kaminski","id":11,"position":"Chief Design Engineer","department":"Research and Development","email":"fkaminskia@xinhuanet.com"},
{"avatar":"https://robohash.org/suscipitiureoccaecati.png?size=50x50&set=set1","name":"Halsy Robshaw","id":12,"position":"Analog Circuit Design manager","department":"Human Resources","email":"hrobshawb@gmpg.org"},
{"avatar":"https://robohash.org/undedoloremaut.png?size=50x50&set=set1","name":"Meredith Gowling","id":13,"position":"Senior Sales Associate","department":"Accounting","email":"mgowlingc@altervista.org"},
{"avatar":"https://robohash.org/etadipiscirepellat.png?size=50x50&set=set1","name":"Abdel Hugonneau","id":14,"position":"Electrical Engineer","department":"Research and Development","email":"ahugonneaud@delicious.com"},
{"avatar":"https://robohash.org/perspiciatisveniamnihil.bmp?size=50x50&set=set1","name":"Ellery Dunlap","id":15,"position":"Technical Writer","department":"Product Management","email":"edunlape@yandex.ru"},
{"avatar":"https://robohash.org/etetesse.bmp?size=50x50&set=set1","name":"Delano Newe","id":16,"position":"Financial Analyst","department":"Accounting","email":"dnewef@elegantthemes.com"},
{"avatar":"https://robohash.org/similiquehicnatus.png?size=50x50&set=set1","name":"Pia Witherow","id":17,"position":"Senior Developer","department":"Training","email":"pwitherowg@timesonline.co.uk"},
{"avatar":"https://robohash.org/idconsecteturet.png?size=50x50&set=set1","name":"Lillis Dotterill","id":18,"position":"Recruiter","department":"Engineering","email":"ldotterillh@hubpages.com"},
{"avatar":"https://robohash.org/etdoloressunt.bmp?size=50x50&set=set1","name":"Ellie Ludye","id":19,"position":"Junior Executive","department":"Marketing","email":"eludyei@hostgator.com"},
{"avatar":"https://robohash.org/cumqueperspiciatissit.bmp?size=50x50&set=set1","name":"Valery McAvinchey","id":20,"position":"VP Product Management","department":"Sales","email":"vmcavincheyj@zdnet.com"},
{"avatar":"https://robohash.org/aliasmolestiasillum.bmp?size=50x50&set=set1","name":"Alice Cannam","id":21,"position":"Safety Technician II","department":"Accounting","email":"acannamk@slideshare.net"},
{"avatar":"https://robohash.org/rerumetcupiditate.jpg?size=50x50&set=set1","name":"Cherrita Grimes","id":22,"position":"Clinical Specialist","department":"Marketing","email":"cgrimesl@samsung.com"},
{"avatar":"https://robohash.org/etaccusamusfugit.png?size=50x50&set=set1","name":"Oona Copping","id":23,"position":"Help Desk Operator","department":"Sales","email":"ocoppingm@people.com.cn"},
{"avatar":"https://robohash.org/inciduntiustonesciunt.png?size=50x50&set=set1","name":"Beltran Duck","id":24,"position":"Assistant Professor","department":"Product Management","email":"bduckn@omniture.com"},
{"avatar":"https://robohash.org/autdelectuslaborum.png?size=50x50&set=set1","name":"Mohandis Climo","id":25,"position":"Environmental Specialist","department":"Sales","email":"mclimoo@gnu.org"},
{"avatar":"https://robohash.org/quilaboremolestiae.jpg?size=50x50&set=set1","name":"Kara-lynn Chippin","id":26,"position":"Health Coach I","department":"Accounting","email":"kchippinp@patch.com"},
{"avatar":"https://robohash.org/eumoccaecatiexplicabo.jpg?size=50x50&set=set1","name":"Sterling Jardein","id":27,"position":"Sales Associate","department":"Accounting","email":"sjardeinq@dailymail.co.uk"},
{"avatar":"https://robohash.org/utquasisapiente.png?size=50x50&set=set1","name":"Timmie Bollands","id":28,"position":"Quality Engineer","department":"Legal","email":"tbollandsr@eventbrite.com"},
{"avatar":"https://robohash.org/voluptastemporaaspernatur.bmp?size=50x50&set=set1","name":"Bari Clapson","id":29,"position":"Computer Systems Analyst I","department":"Sales","email":"bclapsons@ox.ac.uk"},
{"avatar":"https://robohash.org/eumquaeratvoluptatem.jpg?size=50x50&set=set1","name":"Lindy Westney","id":30,"position":"Professor","department":"Support","email":"lwestneyt@biglobe.ne.jp"},
{"avatar":"https://robohash.org/essedoloremquedolor.png?size=50x50&set=set1","name":"Cece Benesevich","id":31,"position":"Senior Developer","department":"Support","email":"cbenesevichu@eventbrite.com"},
{"avatar":"https://robohash.org/voluptatemcommodidolorum.bmp?size=50x50&set=set1","name":"Iggy Crombie","id":32,"position":"Software Consultant","department":"Research and Development","email":"icrombiev@huffingtonpost.com"},
{"avatar":"https://robohash.org/sedplaceatconsequatur.png?size=50x50&set=set1","name":"Norrie Yo","id":33,"position":"Chemical Engineer","department":"Training","email":"nyow@sciencedaily.com"},
{"avatar":"https://robohash.org/teneturquisquasi.bmp?size=50x50&set=set1","name":"Ernest McOnie","id":34,"position":"Analyst Programmer","department":"Services","email":"emconiex@artisteer.com"},
{"avatar":"https://robohash.org/voluptatumdoloresut.jpg?size=50x50&set=set1","name":"Bernice Studders","id":35,"position":"Editor","department":"Engineering","email":"bstuddersy@sina.com.cn"},
{"avatar":"https://robohash.org/corruptinesciuntut.png?size=50x50&set=set1","name":"Fionna O'Hollegan","id":36,"position":"VP Accounting","department":"Legal","email":"foholleganz@salon.com"},
{"avatar":"https://robohash.org/solutadelectusnulla.bmp?size=50x50&set=set1","name":"Vanna Jaggar","id":37,"position":"Project Manager","department":"Business Development","email":"vjaggar10@hc360.com"},
{"avatar":"https://robohash.org/temporeautiste.bmp?size=50x50&set=set1","name":"Fancy Terlinden","id":38,"position":"Sales Associate","department":"Research and Development","email":"fterlinden11@amazon.com"},
{"avatar":"https://robohash.org/praesentiumexplicaboaliquam.jpg?size=50x50&set=set1","name":"Cecil Roubeix","id":39,"position":"Graphic Designer","department":"Business Development","email":"croubeix12@cbsnews.com"},
{"avatar":"https://robohash.org/ducimusinventoreid.bmp?size=50x50&set=set1","name":"Elisabetta Gumbley","id":40,"position":"Technical Writer","department":"Training","email":"egumbley13@fc2.com"},
{"avatar":"https://robohash.org/isteeiusnihil.bmp?size=50x50&set=set1","name":"Rana Flemmich","id":41,"position":"General Manager","department":"Legal","email":"rflemmich14@howstuffworks.com"},
{"avatar":"https://robohash.org/suntautipsam.jpg?size=50x50&set=set1","name":"Dalila Ide","id":42,"position":"Web Developer III","department":"Accounting","email":"dide15@de.vu"},
{"avatar":"https://robohash.org/vitaenequeut.jpg?size=50x50&set=set1","name":"Cherrita Schoenfisch","id":43,"position":"Graphic Designer","department":"Research and Development","email":"cschoenfisch16@histats.com"},
{"avatar":"https://robohash.org/voluptatempraesentiumreiciendis.png?size=50x50&set=set1","name":"Sande Patshull","id":44,"position":"Editor","department":"Marketing","email":"spatshull17@ibm.com"},
{"avatar":"https://robohash.org/quiaofficiislaudantium.bmp?size=50x50&set=set1","name":"Catherin Brazel","id":45,"position":"Structural Engineer","department":"Research and Development","email":"cbrazel18@tmall.com"},
{"avatar":"https://robohash.org/aliquamautemplaceat.jpg?size=50x50&set=set1","name":"Kurtis Kinforth","id":46,"position":"Quality Control Specialist","department":"Legal","email":"kkinforth19@gizmodo.com"},
{"avatar":"https://robohash.org/illoexveritatis.png?size=50x50&set=set1","name":"Tuesday Bergeon","id":47,"position":"Payment Adjustment Coordinator","department":"Human Resources","email":"tbergeon1a@csmonitor.com"},
{"avatar":"https://robohash.org/namdoloresdolorem.jpg?size=50x50&set=set1","name":"Eden Blundell","id":48,"position":"Associate Professor","department":"Support","email":"eblundell1b@typepad.com"},
{"avatar":"https://robohash.org/velitrecusandaevoluptates.jpg?size=50x50&set=set1","name":"Alissa Verissimo","id":49,"position":"Geological Engineer","department":"Business Development","email":"averissimo1c@biblegateway.com"},
{"avatar":"https://robohash.org/impedititaquereprehenderit.png?size=50x50&set=set1","name":"Harriott Summerly","id":50,"position":"Sales Associate","department":"Sales","email":"hsummerly1d@intel.com"}];
